### ISSUE TITLE
Contribute - Missing Packages

### ISSUE THREAD

**Issue by nhudacin** [gocd-contrib/xunit-converter-task#2]
I'm not sure if this is normal with java projects but when I clone the repo and open it up in my ide, I get 6 compilation errors. I'm not sure if this is because of a different java sdk version, missing dependency calls in the maven file,  or something else. Hoping you would be able to help and possibly update the documentation so this won't happen to future contributors.

Thanks!

IDE:  IntelliJ IDEA 14.1.2
JDK: 1.8 (64-bit)
OS: Windows 7 (64-bit)
Messages: 

Information:Using javac 1.8.0_45 to compile java sources
Information:java:

```
Errors occurred while compiling module 'xunit-converter-task'
Information:4/22/2015 9:45 AM - Compilation completed with 6 errors and 0 warnings in 3s 131ms
C:\_SourceControl\NHGIT\xunit-converter-task\src\main\java\com\tw\go\plugin\task\xunit\XUnitConverterTaskExecutor.java
Error:(5, 30) java: package com.tw.xunit.converter does not exist
Error:(29, 17) java: cannot find symbol
  symbol:   class TestReportConverter
  location: class com.tw.go.plugin.task.xunit.XUnitConverterTaskExecutor
C:\_SourceControl\NHGIT\xunit-converter-task\src\main\java\com\tw\go\plugin\task\xunit\XUnitConverterTask.java
Error:(10, 30) java: package com.tw.xunit.converter does not exist
Error:(11, 29) java: package org.apache.commons.io does not exist
Error:(44, 28) java: cannot find symbol
  symbol: variable IOUtils
Error:(66, 14) java: cannot find symbol
  symbol:   variable TestReportConverter
  location: class com.tw.go.plugin.task.xunit.XUnitConverterTask
```

**Comment by srinivasupadhya** [comment]
Clone [XUnit Converter](https://github.com/srinivasupadhya/xunit-converter). Build it with `mvn clean install -DskipTests` & try again.

**Comment by nhudacin** [comment]
That helped.. I still got errors with the reference to org.apache.commons.io but was able to fix it by modifying the pom.xml and reimporting the dependency modules. Will submit a pull request for this issue (if interested).. thanks!

**Comment by srinivasupadhya** [comment]
the `commons-io` dependency should come from `xunit-converter` ([code](https://github.com/srinivasupadhya/xunit-converter/blob/master/pom.xml#L35)).
i have updated [Readme](https://github.com/srinivasupadhya/xunit-converter-task). See if that helps.

**Comment by nhudacin** [comment]
OK.. That makes sense. I hadn't gotten that far yet. Thank you for the help!! You can close this pull request and issue.
